import Header from "@/ui/header";
import SearchInput from "@/ui/search-input";
import Footer from "@/ui/footer";
import AudioDrawerCtxProvider from "@/context/audio-drawer-ctx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={`bg-[#131418]`}>
        <AudioDrawerCtxProvider>
          <header className="xl:10 2xl:12 container mx-auto flex items-center justify-between px-4 py-6 pt-2 md:px-6 lg:px-8">
            <Header />
          </header>
          <SearchInput />

          {children}

          <Footer />
        </AudioDrawerCtxProvider>
      </body>
    </html>
  );
}
